services:
  mysql:
    container_name: 'mysql'
    image: 'mysql:8.0.39'
    environment:
      - 'MYSQL_DATABASE=scherer_eshop'
      - 'MYSQL_USER=eshop'
      - 'MYSQL_PASSWORD=eshop123'
      - 'MYSQL_ROOT_PASSWORD=adminadmin'
    ports:
      - '3306:3306'

  redis:
    container_name: 'redis'
    image: 'redis:7.2.4'
    restart: 'unless-stopped'
    ports:
      - '6379:6379'