services:
  mysql:
    image: mysql:8.0.39
    env_file: ./env/mysql.env
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 10

  app:
#    image: cleytonscherer/eshop-api:latest
    build:
      context: .
    env_file: ./env/app.env
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy

  redis:
    image: redis:7.2.4
    restart: unless-stopped

volumes:
  mysql-data: